# Generated by Django 6.0.6 on 2026-06-23 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand_name', models.CharField(max_length=50)),
                ('Brand_description', models.TextField()),
                ('Brand_logo', models.ImageField(upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Furniture_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Pictures', models.ImageField(upload_to='photos')),
                ('Description', models.TextField()),
                ('Category_added', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_typename', models.CharField(choices=[('user', 'User'), ('buyer', 'Buyer'), ('seller', 'Seller'), ('rent', 'Rent')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='New_furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('New_Furniture_Name', models.CharField(max_length=50)),
                ('New_Furniture_Description', models.TextField()),
                ('New_Furniture_Price', models.FloatField()),
                ('New_Furniture_Image', models.ImageField(upload_to='photos')),
                ('New_Furniture_Available_Quantity', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], max_length=10)),
                ('New_Furniture_Brand_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wood.brand_table')),
                ('New_Furniture_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wood.furniture_category')),
            ],
        ),
        migrations.CreateModel(
            name='Old_furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Old_Furniture_Name', models.CharField(max_length=50)),
                ('Old_Furniture_Description', models.TextField()),
                ('Old_Furniture_Price', models.FloatField()),
                ('Old_Furniture_Image', models.ImageField(upload_to='photos')),
                ('Old_Furniture_Available_Quantity', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], max_length=10)),
                ('Old_Furniture_Brand_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wood.brand_table')),
                ('Old_Furniture_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wood.furniture_category')),
            ],
        ),
        migrations.CreateModel(
            name='Rent_furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rent_Furniture_Name', models.CharField(max_length=50)),
                ('Rent_Furniture_Description', models.TextField()),
                ('Rent_Furniture_Price', models.FloatField()),
                ('Rent_Furniture_Image', models.ImageField(upload_to='photos')),
                ('Rent_Furniture_Available_Quantity', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], max_length=10)),
                ('Rent_Furniture_Brand_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wood.brand_table')),
                ('Rent_Furniture_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wood.furniture_category')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State_name', models.CharField(max_length=30)),
                ('Country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wood.country')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City_name', models.CharField(max_length=30)),
                ('State_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wood.state')),
            ],
        ),
        migrations.CreateModel(
            name='User_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=30)),
                ('Dp', models.ImageField(upload_to='photos')),
                ('Gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.BigIntegerField()),
                ('Status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=10)),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wood.role')),
            ],
        ),
        migrations.CreateModel(
            name='User_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Building_name', models.CharField(max_length=40)),
                ('Street_name', models.CharField(max_length=40)),
                ('Pincode', models.IntegerField()),
                ('City_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wood.city')),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wood.user_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Rent_Furniture_Buying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rent_StartDate', models.DateField()),
                ('Rent_EndDate', models.DateField()),
                ('Rent_Book_DateTime', models.DateTimeField()),
                ('Rent_Furniture_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wood.rent_furniture')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wood.user_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Old_Furniture_Buying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Old_Book_DateTime', models.DateTimeField()),
                ('Old_Furniture_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wood.old_furniture')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wood.user_detail')),
            ],
        ),
        migrations.CreateModel(
            name='New_Furniture_Buying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('New_Book_DateTime', models.DateTimeField()),
                ('New_Furniture_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wood.new_furniture')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wood.user_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Feedback_on', models.DateTimeField(auto_now=True)),
                ('Feedback_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wood.user_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Complain_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complain_name', models.CharField(max_length=50)),
                ('Details', models.TextField()),
                ('Photo', models.ImageField(upload_to='photos')),
                ('Complain_on', models.DateTimeField(auto_now=True)),
                ('Complain_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wood.user_detail')),
            ],
        ),
    ]
